### ISSUE TITLE
Misc TODO items

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#20]
- [x] joblib must be replaced by shelve

- [x] _path_static should be renamed path_static, as it is used in the conf.py

- [x] the css names should be harmonized. In particular,  they should be all given a prefix, such as sphx-glr-...

- [x] functions should not be defined in closures: _select_block, _parse_dict_structure must be moved out of the function where they are defined

- [x] no @author in docstrings, but author as a comment in the beginning of a file,  with also the full name of the author, the original authors if any,  and "license: BSD"

- [x] the code isn't completely pep8: there should be two empty lines between first level functions

**Comment by Titan-C** [comment]
https://github.com/nilearn/nilearn/pull/399 contains comments on pep8 changes to be completed

**Comment by lesteve** [comment]
> nilearn/nilearn#399 contains comments on pep8 changes to be completed

I ran autopep8 on sphinxgallery, examples and tutorials folders so we should be fine regarding PEP8 now.
