### ISSUE TITLE
BUG: Bugs with backref links

### ISSUE THREAD

**Issue by larsoner** [sphinx-gallery/sphinx-gallery#587]
Here are bugs I've seen with the backref links:

- [x] Class instances after creation sometimes [only get](https://github.com/mne-tools/mne-python/pull/7181#issuecomment-571685516) the `sphx-glr-backref-module-mne` class, not `sphx-glr-backref-type-class` and `sphx-glr-backref-instance` -- see also #588 (addressed in #591)
- [x] `np.random.RandomState` does not link properly (#593)
- [x] Method parsing is incomplete, in MNE things like `ica.plot_properties` do not link even though they should. This could be because of greedy replacement of `ica` occurring before `ica.plot_properties` can be replaced, or could be a problem with `get_mapping` (or downstream of there) (#596).
- [ ] There are [extra / incorrect backrefs](https://github.com/sphinx-gallery/sphinx-gallery/pull/584#issuecomment-571601897)

Hopefully to be fixed by follow-up PRs.

**Comment by lucyleeow** [comment]
@larsoner number 2 `np.random.RandomState` is because it doesn't exist in the intersphinx named inventory.

I tried this on the template sample project and wrote `intersphinx_inv` -
```
intersphinx_inv = getattr(app.env, 'intersphinx_named_inventory', dict())
```
from [`_embed_code_links()`](https://github.com/sphinx-gallery/sphinx-gallery/blob/4cee8a0e82dc41ee58ce94214fd79eb808107dd4/sphinx_gallery/docs_resolv.py#L306) to a file - [intersphinx.txt](https://github.com/sphinx-gallery/sphinx-gallery/files/4047148/intersphinx.txt).

The intersphinx part of `conf.py` file looks like this:
```
intersphinx_mapping = {
    'python': ('https://docs.python.org/{.major}'.format(sys.version_info), None),
    'matplotlib': ('https://matplotlib.org/', None),
    'pandas': ('https://pandas.pydata.org/', None),
    'numpy': ('https://docs.scipy.org/doc/numpy', None),
}
```

Interestingly `pandas.Dataframe()` also does not exist - accordingly it is not linked in our [docs](https://sphinx-gallery.github.io/dev/auto_examples/plot_3_capture_repr.html) either.

Not familiar with intersphinx so not sure how to pursue this. What do you suggest?



(will look at your PR soon)

**Comment by larsoner** [comment]
I have a fix almost complete for that too

**Comment by lucyleeow** [comment]
@larsoner I was mistaken with the [extra/incorrect backreferences](https://github.com/sphinx-gallery/sphinx-gallery/pull/584#issuecomment-571601897). They are actually correct because the function was referred to in the text (but not the code) of the example. Unless this is unwanted behaviour I think this can be removed.

**Comment by larsoner** [comment]
Great!
